[package]
name = "advent-2023"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6.9"
nom = "7.1.3"
strum = { version = "0.25.0", features = ["derive"] }

[[bin]]
name = "day1"
path = "src/bin/day1/day1.rs"

[[bin]]
name = "day2"
path = "src/bin/day2/day2.rs"
